### ISSUE TITLE
Support for Magnolia 6.3

### ISSUE THREAD

**Issue by pierresandrin-oi** [IBM/magkit-vanity-url#16]
Hello!
I tested the vanityUrls App version 1.6.4 on Magnolia 6.3.0 and found some issues. Will there be a working version for 6.3?

The Issues I found are:

- Error message when saving a Entry (but the entry is still saved)

- There redirect is not executed

I didn't try to debug deeper on why these Errors happen...

**Comment by serialcool** [comment]
`[INFO] [talledLocalContainer] Caused by: java.lang.NoSuchMethodError: 'void info.magnolia.ui.observation.DatasourceObservation$Manual.trigger()'
[INFO] [talledLocalContainer]   at de.ibmix.magkit.vanityurl.app.VanityUrlSaveFormAction.lambda$write$0(VanityUrlSaveFormAction.java:152) ~[magkit-vanity-url-1.6.4.jar:?]
[INFO] [talledLocalContainer]   at com.machinezoo.noexception.CheckedExceptionHandler$CheckedConsumer.accept(CheckedExceptionHandler.java:320) ~[noexception-1.9.1.jar:?]
[INFO] [talledLocalContainer]   at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
[INFO] [talledLocalContainer]   at de.ibmix.magkit.vanityurl.app.VanityUrlSaveFormAction.write(VanityUrlSaveFormAction.java:146) ~[magkit-vanity-url-1.6.4.jar:?]
[INFO] [talledLocalContainer]   at info.magnolia.ui.contentapp.action.CommitAction.execute(CommitAction.java:85) ~[magnolia-ui-framework-6.3.0.jar:?]
[INFO] [talledLocalContainer]   at info.magnolia.ui.api.action.AbstractActionExecutor.execute(AbstractActionExecutor.java:62) ~[magnolia-ui-api-6.3.0.jar:?]
[INFO] [talledLocalContainer]   at info.magnolia.ui.contentapp.browser.ActionExecutionService.executeAction(ActionExecutionService.java:70) ~[magnolia-ui-framework-6.3.0.jar:?]
[INFO] [talledLocalContainer]   at info.magnolia.ui.framework.action.service.CompatibilityActionExecutionService.executeAction(CompatibilityActionExecutionService.java:129) ~[magnolia-ui-framework-compatibility-6.3.0.jar:?]`

**Comment by Eagle94T** [comment]
We just tested the 1.7.0-SNAPSHOT version with magnolia 6.3, and it worked as expected. 

When can we expect to have a release-version? 

Or are there any reason, to not release it?

p.s. https://www.magnolia-cms.com/marketplace/detail/vanity-url.html points to the old repository

**Comment by serialcool** [comment]
Version 1.7.0 was released and with that the first 6.3 compatible version is available.
